#!/bin/sh

PROG="hardcoded-layout-simple-query join-and-aggr html-users-list \
       current-time date-types \
       insert-update-delete test-bounded transaction"

for p in $PROG; do
	echo "Running: $p"
	./$p "$@"
done