#!/bin/sh

PROG="hardcoded-layout-simple-query join-and-aggr html-users-list \
       current-time date-types \
       insert-update-delete test-bounded transaction big-test"

# make sure TestConnect.hs exists
make TestConnect.hs

echo "Deleting old database definitions..."
rm -rf Dp037*
echo

echo "Running DbDirect..."
../build/ghc/DBDirect "$@" Dp037 || exit 1
echo

echo "Running DbDirect -b..."
../build/ghc/DBDirect -b "$@" Dp037_bounded || exit 1
echo

# run tests with ghc
for p in $PROG; do
	echo "GHC compiling $p"
	make $p || exit 1
	echo "GHC running: $p"
	./$p "$@"
done

# run tests with hugs
for p in $PROG; do
	echo "Hugs running: $p"
	runhugs -98 +o $p.hs "$@"
done