{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack60 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module DB1.Hdb_t1 where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type Hdb_t1 =
    (RecCons T1f01 (Expr (Maybe String))
     (RecCons T1f02 (Expr String)
      (RecCons T1f03 (Expr (Maybe String))
       (RecCons T1f04 (Expr String)
        (RecCons T1f05 (Expr (Maybe Int))
         (RecCons T1f06 (Expr Int)
          (RecCons T1f07 (Expr (Maybe Int))
           (RecCons T1f08 (Expr Int)
            (RecCons T1f09 (Expr (Maybe Integer))
             (RecCons T1f10 (Expr Integer)
              (RecCons T1f11 (Expr (Maybe Integer))
               (RecCons T1f12 (Expr Integer)
                (RecCons T1f13 (Expr (Maybe Double))
                 (RecCons T1f14 (Expr Double)
                  (RecCons T1f15 (Expr (Maybe Double))
                   (RecCons T1f16 (Expr Double)
                    (RecCons T1f21 (Expr (Maybe CalendarTime))
                     (RecCons T1f22 (Expr CalendarTime)
                      (RecCons T1f23 (Expr (Maybe CalendarTime))
                       (RecCons T1f24 (Expr CalendarTime) RecNil))))))))))))))))))))

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
hdb_t1 :: Table Hdb_t1
hdb_t1 = baseTable "hdb_t1" $
         hdbMakeEntry T1f01 #
         hdbMakeEntry T1f02 #
         hdbMakeEntry T1f03 #
         hdbMakeEntry T1f04 #
         hdbMakeEntry T1f05 #
         hdbMakeEntry T1f06 #
         hdbMakeEntry T1f07 #
         hdbMakeEntry T1f08 #
         hdbMakeEntry T1f09 #
         hdbMakeEntry T1f10 #
         hdbMakeEntry T1f11 #
         hdbMakeEntry T1f12 #
         hdbMakeEntry T1f13 #
         hdbMakeEntry T1f14 #
         hdbMakeEntry T1f15 #
         hdbMakeEntry T1f16 #
         hdbMakeEntry T1f21 #
         hdbMakeEntry T1f22 #
         hdbMakeEntry T1f23 #
         hdbMakeEntry T1f24

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- T1f01 Field
---------------------------------------------------------------------------

data T1f01 = T1f01

instance FieldTag T1f01 where fieldName _ = "t1f01"

t1f01 :: Attr T1f01 (Maybe String)
t1f01 = mkAttr T1f01

---------------------------------------------------------------------------
-- T1f02 Field
---------------------------------------------------------------------------

data T1f02 = T1f02

instance FieldTag T1f02 where fieldName _ = "t1f02"

t1f02 :: Attr T1f02 String
t1f02 = mkAttr T1f02

---------------------------------------------------------------------------
-- T1f03 Field
---------------------------------------------------------------------------

data T1f03 = T1f03

instance FieldTag T1f03 where fieldName _ = "t1f03"

t1f03 :: Attr T1f03 (Maybe String)
t1f03 = mkAttr T1f03

---------------------------------------------------------------------------
-- T1f04 Field
---------------------------------------------------------------------------

data T1f04 = T1f04

instance FieldTag T1f04 where fieldName _ = "t1f04"

t1f04 :: Attr T1f04 String
t1f04 = mkAttr T1f04

---------------------------------------------------------------------------
-- T1f05 Field
---------------------------------------------------------------------------

data T1f05 = T1f05

instance FieldTag T1f05 where fieldName _ = "t1f05"

t1f05 :: Attr T1f05 (Maybe Int)
t1f05 = mkAttr T1f05

---------------------------------------------------------------------------
-- T1f06 Field
---------------------------------------------------------------------------

data T1f06 = T1f06

instance FieldTag T1f06 where fieldName _ = "t1f06"

t1f06 :: Attr T1f06 Int
t1f06 = mkAttr T1f06

---------------------------------------------------------------------------
-- T1f07 Field
---------------------------------------------------------------------------

data T1f07 = T1f07

instance FieldTag T1f07 where fieldName _ = "t1f07"

t1f07 :: Attr T1f07 (Maybe Int)
t1f07 = mkAttr T1f07

---------------------------------------------------------------------------
-- T1f08 Field
---------------------------------------------------------------------------

data T1f08 = T1f08

instance FieldTag T1f08 where fieldName _ = "t1f08"

t1f08 :: Attr T1f08 Int
t1f08 = mkAttr T1f08

---------------------------------------------------------------------------
-- T1f09 Field
---------------------------------------------------------------------------

data T1f09 = T1f09

instance FieldTag T1f09 where fieldName _ = "t1f09"

t1f09 :: Attr T1f09 (Maybe Integer)
t1f09 = mkAttr T1f09

---------------------------------------------------------------------------
-- T1f10 Field
---------------------------------------------------------------------------

data T1f10 = T1f10

instance FieldTag T1f10 where fieldName _ = "t1f10"

t1f10 :: Attr T1f10 Integer
t1f10 = mkAttr T1f10

---------------------------------------------------------------------------
-- T1f11 Field
---------------------------------------------------------------------------

data T1f11 = T1f11

instance FieldTag T1f11 where fieldName _ = "t1f11"

t1f11 :: Attr T1f11 (Maybe Integer)
t1f11 = mkAttr T1f11

---------------------------------------------------------------------------
-- T1f12 Field
---------------------------------------------------------------------------

data T1f12 = T1f12

instance FieldTag T1f12 where fieldName _ = "t1f12"

t1f12 :: Attr T1f12 Integer
t1f12 = mkAttr T1f12

---------------------------------------------------------------------------
-- T1f13 Field
---------------------------------------------------------------------------

data T1f13 = T1f13

instance FieldTag T1f13 where fieldName _ = "t1f13"

t1f13 :: Attr T1f13 (Maybe Double)
t1f13 = mkAttr T1f13

---------------------------------------------------------------------------
-- T1f14 Field
---------------------------------------------------------------------------

data T1f14 = T1f14

instance FieldTag T1f14 where fieldName _ = "t1f14"

t1f14 :: Attr T1f14 Double
t1f14 = mkAttr T1f14

---------------------------------------------------------------------------
-- T1f15 Field
---------------------------------------------------------------------------

data T1f15 = T1f15

instance FieldTag T1f15 where fieldName _ = "t1f15"

t1f15 :: Attr T1f15 (Maybe Double)
t1f15 = mkAttr T1f15

---------------------------------------------------------------------------
-- T1f16 Field
---------------------------------------------------------------------------

data T1f16 = T1f16

instance FieldTag T1f16 where fieldName _ = "t1f16"

t1f16 :: Attr T1f16 Double
t1f16 = mkAttr T1f16

---------------------------------------------------------------------------
-- T1f21 Field
---------------------------------------------------------------------------

data T1f21 = T1f21

instance FieldTag T1f21 where fieldName _ = "t1f21"

t1f21 :: Attr T1f21 (Maybe CalendarTime)
t1f21 = mkAttr T1f21

---------------------------------------------------------------------------
-- T1f22 Field
---------------------------------------------------------------------------

data T1f22 = T1f22

instance FieldTag T1f22 where fieldName _ = "t1f22"

t1f22 :: Attr T1f22 CalendarTime
t1f22 = mkAttr T1f22

---------------------------------------------------------------------------
-- T1f23 Field
---------------------------------------------------------------------------

data T1f23 = T1f23

instance FieldTag T1f23 where fieldName _ = "t1f23"

t1f23 :: Attr T1f23 (Maybe CalendarTime)
t1f23 = mkAttr T1f23

---------------------------------------------------------------------------
-- T1f24 Field
---------------------------------------------------------------------------

data T1f24 = T1f24

instance FieldTag T1f24 where fieldName _ = "t1f24"

t1f24 :: Attr T1f24 CalendarTime
t1f24 = mkAttr T1f24
