{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack60 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module DB1.Hdb_t2 where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type Hdb_t2 =
    (RecCons T2f01 (Expr (Maybe String))
     (RecCons T2f02 (Expr String)
      (RecCons T2f03 (Expr (Maybe String))
       (RecCons T2f04 (Expr String)
        (RecCons T2f05 (Expr (Maybe Int))
         (RecCons T2f06 (Expr Int)
          (RecCons T2f07 (Expr (Maybe Int))
           (RecCons T2f08 (Expr Int)
            (RecCons T2f09 (Expr (Maybe Integer))
             (RecCons T2f10 (Expr Integer)
              (RecCons T2f11 (Expr (Maybe Integer))
               (RecCons T2f12 (Expr Integer)
                (RecCons T2f13 (Expr (Maybe Double))
                 (RecCons T2f14 (Expr Double)
                  (RecCons T2f15 (Expr (Maybe Double))
                   (RecCons T2f16 (Expr Double)
                    (RecCons T2f21 (Expr (Maybe CalendarTime))
                     (RecCons T2f22 (Expr CalendarTime)
                      (RecCons T2f23 (Expr (Maybe CalendarTime))
                       (RecCons T2f24 (Expr CalendarTime) RecNil))))))))))))))))))))

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
hdb_t2 :: Table Hdb_t2
hdb_t2 = baseTable "hdb_t2" $
         hdbMakeEntry T2f01 #
         hdbMakeEntry T2f02 #
         hdbMakeEntry T2f03 #
         hdbMakeEntry T2f04 #
         hdbMakeEntry T2f05 #
         hdbMakeEntry T2f06 #
         hdbMakeEntry T2f07 #
         hdbMakeEntry T2f08 #
         hdbMakeEntry T2f09 #
         hdbMakeEntry T2f10 #
         hdbMakeEntry T2f11 #
         hdbMakeEntry T2f12 #
         hdbMakeEntry T2f13 #
         hdbMakeEntry T2f14 #
         hdbMakeEntry T2f15 #
         hdbMakeEntry T2f16 #
         hdbMakeEntry T2f21 #
         hdbMakeEntry T2f22 #
         hdbMakeEntry T2f23 #
         hdbMakeEntry T2f24

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- T2f01 Field
---------------------------------------------------------------------------

data T2f01 = T2f01

instance FieldTag T2f01 where fieldName _ = "t2f01"

t2f01 :: Attr T2f01 (Maybe String)
t2f01 = mkAttr T2f01

---------------------------------------------------------------------------
-- T2f02 Field
---------------------------------------------------------------------------

data T2f02 = T2f02

instance FieldTag T2f02 where fieldName _ = "t2f02"

t2f02 :: Attr T2f02 String
t2f02 = mkAttr T2f02

---------------------------------------------------------------------------
-- T2f03 Field
---------------------------------------------------------------------------

data T2f03 = T2f03

instance FieldTag T2f03 where fieldName _ = "t2f03"

t2f03 :: Attr T2f03 (Maybe String)
t2f03 = mkAttr T2f03

---------------------------------------------------------------------------
-- T2f04 Field
---------------------------------------------------------------------------

data T2f04 = T2f04

instance FieldTag T2f04 where fieldName _ = "t2f04"

t2f04 :: Attr T2f04 String
t2f04 = mkAttr T2f04

---------------------------------------------------------------------------
-- T2f05 Field
---------------------------------------------------------------------------

data T2f05 = T2f05

instance FieldTag T2f05 where fieldName _ = "t2f05"

t2f05 :: Attr T2f05 (Maybe Int)
t2f05 = mkAttr T2f05

---------------------------------------------------------------------------
-- T2f06 Field
---------------------------------------------------------------------------

data T2f06 = T2f06

instance FieldTag T2f06 where fieldName _ = "t2f06"

t2f06 :: Attr T2f06 Int
t2f06 = mkAttr T2f06

---------------------------------------------------------------------------
-- T2f07 Field
---------------------------------------------------------------------------

data T2f07 = T2f07

instance FieldTag T2f07 where fieldName _ = "t2f07"

t2f07 :: Attr T2f07 (Maybe Int)
t2f07 = mkAttr T2f07

---------------------------------------------------------------------------
-- T2f08 Field
---------------------------------------------------------------------------

data T2f08 = T2f08

instance FieldTag T2f08 where fieldName _ = "t2f08"

t2f08 :: Attr T2f08 Int
t2f08 = mkAttr T2f08

---------------------------------------------------------------------------
-- T2f09 Field
---------------------------------------------------------------------------

data T2f09 = T2f09

instance FieldTag T2f09 where fieldName _ = "t2f09"

t2f09 :: Attr T2f09 (Maybe Integer)
t2f09 = mkAttr T2f09

---------------------------------------------------------------------------
-- T2f10 Field
---------------------------------------------------------------------------

data T2f10 = T2f10

instance FieldTag T2f10 where fieldName _ = "t2f10"

t2f10 :: Attr T2f10 Integer
t2f10 = mkAttr T2f10

---------------------------------------------------------------------------
-- T2f11 Field
---------------------------------------------------------------------------

data T2f11 = T2f11

instance FieldTag T2f11 where fieldName _ = "t2f11"

t2f11 :: Attr T2f11 (Maybe Integer)
t2f11 = mkAttr T2f11

---------------------------------------------------------------------------
-- T2f12 Field
---------------------------------------------------------------------------

data T2f12 = T2f12

instance FieldTag T2f12 where fieldName _ = "t2f12"

t2f12 :: Attr T2f12 Integer
t2f12 = mkAttr T2f12

---------------------------------------------------------------------------
-- T2f13 Field
---------------------------------------------------------------------------

data T2f13 = T2f13

instance FieldTag T2f13 where fieldName _ = "t2f13"

t2f13 :: Attr T2f13 (Maybe Double)
t2f13 = mkAttr T2f13

---------------------------------------------------------------------------
-- T2f14 Field
---------------------------------------------------------------------------

data T2f14 = T2f14

instance FieldTag T2f14 where fieldName _ = "t2f14"

t2f14 :: Attr T2f14 Double
t2f14 = mkAttr T2f14

---------------------------------------------------------------------------
-- T2f15 Field
---------------------------------------------------------------------------

data T2f15 = T2f15

instance FieldTag T2f15 where fieldName _ = "t2f15"

t2f15 :: Attr T2f15 (Maybe Double)
t2f15 = mkAttr T2f15

---------------------------------------------------------------------------
-- T2f16 Field
---------------------------------------------------------------------------

data T2f16 = T2f16

instance FieldTag T2f16 where fieldName _ = "t2f16"

t2f16 :: Attr T2f16 Double
t2f16 = mkAttr T2f16

---------------------------------------------------------------------------
-- T2f21 Field
---------------------------------------------------------------------------

data T2f21 = T2f21

instance FieldTag T2f21 where fieldName _ = "t2f21"

t2f21 :: Attr T2f21 (Maybe CalendarTime)
t2f21 = mkAttr T2f21

---------------------------------------------------------------------------
-- T2f22 Field
---------------------------------------------------------------------------

data T2f22 = T2f22

instance FieldTag T2f22 where fieldName _ = "t2f22"

t2f22 :: Attr T2f22 CalendarTime
t2f22 = mkAttr T2f22

---------------------------------------------------------------------------
-- T2f23 Field
---------------------------------------------------------------------------

data T2f23 = T2f23

instance FieldTag T2f23 where fieldName _ = "t2f23"

t2f23 :: Attr T2f23 (Maybe CalendarTime)
t2f23 = mkAttr T2f23

---------------------------------------------------------------------------
-- T2f24 Field
---------------------------------------------------------------------------

data T2f24 = T2f24

instance FieldTag T2f24 where fieldName _ = "t2f24"

t2f24 :: Attr T2f24 CalendarTime
t2f24 = mkAttr T2f24
