{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack60 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module DB1.Hdb_t2 where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type Hdb_t2 =
    Record (HCons (LVPair T2f01 (Expr (Maybe String)))
            (HCons (LVPair T2f02 (Expr String))
             (HCons (LVPair T2f03 (Expr (Maybe String)))
              (HCons (LVPair T2f04 (Expr String))
               (HCons (LVPair T2f05 (Expr (Maybe Int)))
                (HCons (LVPair T2f06 (Expr Int))
                 (HCons (LVPair T2f07 (Expr (Maybe Int)))
                  (HCons (LVPair T2f08 (Expr Int))
                   (HCons (LVPair T2f09 (Expr (Maybe Integer)))
                    (HCons (LVPair T2f10 (Expr Integer))
                     (HCons (LVPair T2f11 (Expr (Maybe Integer)))
                      (HCons (LVPair T2f12 (Expr Integer))
                       (HCons (LVPair T2f13 (Expr (Maybe Double)))
                        (HCons (LVPair T2f14 (Expr Double))
                         (HCons (LVPair T2f15 (Expr (Maybe Double)))
                          (HCons (LVPair T2f16 (Expr Double))
                           (HCons (LVPair T2f21 (Expr (Maybe CalendarTime)))
                            (HCons (LVPair T2f22 (Expr CalendarTime))
                             (HCons (LVPair T2f23 (Expr (Maybe CalendarTime)))
                              (HCons (LVPair T2f24 (Expr CalendarTime)) HNil))))))))))))))))))))

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
hdb_t2 :: Table Hdb_t2
hdb_t2 = baseTable "hdb_t2"

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- T2f01 Field
---------------------------------------------------------------------------

data T2f01Tag
type T2f01 = Proxy T2f01Tag
instance ShowLabel T2f01 where showLabel _ = "t2f01"

t2f01 :: T2f01
t2f01 = proxy

---------------------------------------------------------------------------
-- T2f02 Field
---------------------------------------------------------------------------

data T2f02Tag
type T2f02 = Proxy T2f02Tag
instance ShowLabel T2f02 where showLabel _ = "t2f02"

t2f02 :: T2f02
t2f02 = proxy

---------------------------------------------------------------------------
-- T2f03 Field
---------------------------------------------------------------------------

data T2f03Tag
type T2f03 = Proxy T2f03Tag
instance ShowLabel T2f03 where showLabel _ = "t2f03"

t2f03 :: T2f03
t2f03 = proxy

---------------------------------------------------------------------------
-- T2f04 Field
---------------------------------------------------------------------------

data T2f04Tag
type T2f04 = Proxy T2f04Tag
instance ShowLabel T2f04 where showLabel _ = "t2f04"

t2f04 :: T2f04
t2f04 = proxy

---------------------------------------------------------------------------
-- T2f05 Field
---------------------------------------------------------------------------

data T2f05Tag
type T2f05 = Proxy T2f05Tag
instance ShowLabel T2f05 where showLabel _ = "t2f05"

t2f05 :: T2f05
t2f05 = proxy

---------------------------------------------------------------------------
-- T2f06 Field
---------------------------------------------------------------------------

data T2f06Tag
type T2f06 = Proxy T2f06Tag
instance ShowLabel T2f06 where showLabel _ = "t2f06"

t2f06 :: T2f06
t2f06 = proxy

---------------------------------------------------------------------------
-- T2f07 Field
---------------------------------------------------------------------------

data T2f07Tag
type T2f07 = Proxy T2f07Tag
instance ShowLabel T2f07 where showLabel _ = "t2f07"

t2f07 :: T2f07
t2f07 = proxy

---------------------------------------------------------------------------
-- T2f08 Field
---------------------------------------------------------------------------

data T2f08Tag
type T2f08 = Proxy T2f08Tag
instance ShowLabel T2f08 where showLabel _ = "t2f08"

t2f08 :: T2f08
t2f08 = proxy

---------------------------------------------------------------------------
-- T2f09 Field
---------------------------------------------------------------------------

data T2f09Tag
type T2f09 = Proxy T2f09Tag
instance ShowLabel T2f09 where showLabel _ = "t2f09"

t2f09 :: T2f09
t2f09 = proxy

---------------------------------------------------------------------------
-- T2f10 Field
---------------------------------------------------------------------------

data T2f10Tag
type T2f10 = Proxy T2f10Tag
instance ShowLabel T2f10 where showLabel _ = "t2f10"

t2f10 :: T2f10
t2f10 = proxy

---------------------------------------------------------------------------
-- T2f11 Field
---------------------------------------------------------------------------

data T2f11Tag
type T2f11 = Proxy T2f11Tag
instance ShowLabel T2f11 where showLabel _ = "t2f11"

t2f11 :: T2f11
t2f11 = proxy

---------------------------------------------------------------------------
-- T2f12 Field
---------------------------------------------------------------------------

data T2f12Tag
type T2f12 = Proxy T2f12Tag
instance ShowLabel T2f12 where showLabel _ = "t2f12"

t2f12 :: T2f12
t2f12 = proxy

---------------------------------------------------------------------------
-- T2f13 Field
---------------------------------------------------------------------------

data T2f13Tag
type T2f13 = Proxy T2f13Tag
instance ShowLabel T2f13 where showLabel _ = "t2f13"

t2f13 :: T2f13
t2f13 = proxy

---------------------------------------------------------------------------
-- T2f14 Field
---------------------------------------------------------------------------

data T2f14Tag
type T2f14 = Proxy T2f14Tag
instance ShowLabel T2f14 where showLabel _ = "t2f14"

t2f14 :: T2f14
t2f14 = proxy

---------------------------------------------------------------------------
-- T2f15 Field
---------------------------------------------------------------------------

data T2f15Tag
type T2f15 = Proxy T2f15Tag
instance ShowLabel T2f15 where showLabel _ = "t2f15"

t2f15 :: T2f15
t2f15 = proxy

---------------------------------------------------------------------------
-- T2f16 Field
---------------------------------------------------------------------------

data T2f16Tag
type T2f16 = Proxy T2f16Tag
instance ShowLabel T2f16 where showLabel _ = "t2f16"

t2f16 :: T2f16
t2f16 = proxy

---------------------------------------------------------------------------
-- T2f21 Field
---------------------------------------------------------------------------

data T2f21Tag
type T2f21 = Proxy T2f21Tag
instance ShowLabel T2f21 where showLabel _ = "t2f21"

t2f21 :: T2f21
t2f21 = proxy

---------------------------------------------------------------------------
-- T2f22 Field
---------------------------------------------------------------------------

data T2f22Tag
type T2f22 = Proxy T2f22Tag
instance ShowLabel T2f22 where showLabel _ = "t2f22"

t2f22 :: T2f22
t2f22 = proxy

---------------------------------------------------------------------------
-- T2f23 Field
---------------------------------------------------------------------------

data T2f23Tag
type T2f23 = Proxy T2f23Tag
instance ShowLabel T2f23 where showLabel _ = "t2f23"

t2f23 :: T2f23
t2f23 = proxy

---------------------------------------------------------------------------
-- T2f24 Field
---------------------------------------------------------------------------

data T2f24Tag
type T2f24 = Proxy T2f24Tag
instance ShowLabel T2f24 where showLabel _ = "t2f24"

t2f24 :: T2f24
t2f24 = proxy
