{-# OPTIONS_GHC -fcontext-stack60 #-}
-- NOTE: use GHC flag -fcontext-stack60 with this module if GHC < 6.8.1
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module DB1.Hdb_t1 where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type Hdb_t1 =
    Record (HCons (LVPair T1f01 (Expr (Maybe String)))
            (HCons (LVPair T1f02 (Expr String))
             (HCons (LVPair T1f03 (Expr (Maybe String)))
              (HCons (LVPair T1f04 (Expr String))
               (HCons (LVPair T1f05 (Expr (Maybe Int)))
                (HCons (LVPair T1f06 (Expr Int))
                 (HCons (LVPair T1f07 (Expr (Maybe Int)))
                  (HCons (LVPair T1f08 (Expr Int))
                   (HCons (LVPair T1f09 (Expr (Maybe Integer)))
                    (HCons (LVPair T1f10 (Expr Integer))
                     (HCons (LVPair T1f11 (Expr (Maybe Integer)))
                      (HCons (LVPair T1f12 (Expr Integer))
                       (HCons (LVPair T1f13 (Expr (Maybe Double)))
                        (HCons (LVPair T1f14 (Expr Double))
                         (HCons (LVPair T1f15 (Expr (Maybe Double)))
                          (HCons (LVPair T1f16 (Expr Double))
                           (HCons (LVPair T1f21 (Expr (Maybe CalendarTime)))
                            (HCons (LVPair T1f22 (Expr CalendarTime))
                             (HCons (LVPair T1f23 (Expr (Maybe CalendarTime)))
                              (HCons (LVPair T1f24 (Expr CalendarTime)) HNil))))))))))))))))))))

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
hdb_t1 :: Table Hdb_t1
hdb_t1 = baseTable "hdb_t1"

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- T1f01 Field
---------------------------------------------------------------------------

data T1f01Tag
type T1f01 = Proxy T1f01Tag
instance ShowLabel T1f01 where showLabel _ = "t1f01"

t1f01 :: T1f01
t1f01 = proxy

---------------------------------------------------------------------------
-- T1f02 Field
---------------------------------------------------------------------------

data T1f02Tag
type T1f02 = Proxy T1f02Tag
instance ShowLabel T1f02 where showLabel _ = "t1f02"

t1f02 :: T1f02
t1f02 = proxy

---------------------------------------------------------------------------
-- T1f03 Field
---------------------------------------------------------------------------

data T1f03Tag
type T1f03 = Proxy T1f03Tag
instance ShowLabel T1f03 where showLabel _ = "t1f03"

t1f03 :: T1f03
t1f03 = proxy

---------------------------------------------------------------------------
-- T1f04 Field
---------------------------------------------------------------------------

data T1f04Tag
type T1f04 = Proxy T1f04Tag
instance ShowLabel T1f04 where showLabel _ = "t1f04"

t1f04 :: T1f04
t1f04 = proxy

---------------------------------------------------------------------------
-- T1f05 Field
---------------------------------------------------------------------------

data T1f05Tag
type T1f05 = Proxy T1f05Tag
instance ShowLabel T1f05 where showLabel _ = "t1f05"

t1f05 :: T1f05
t1f05 = proxy

---------------------------------------------------------------------------
-- T1f06 Field
---------------------------------------------------------------------------

data T1f06Tag
type T1f06 = Proxy T1f06Tag
instance ShowLabel T1f06 where showLabel _ = "t1f06"

t1f06 :: T1f06
t1f06 = proxy

---------------------------------------------------------------------------
-- T1f07 Field
---------------------------------------------------------------------------

data T1f07Tag
type T1f07 = Proxy T1f07Tag
instance ShowLabel T1f07 where showLabel _ = "t1f07"

t1f07 :: T1f07
t1f07 = proxy

---------------------------------------------------------------------------
-- T1f08 Field
---------------------------------------------------------------------------

data T1f08Tag
type T1f08 = Proxy T1f08Tag
instance ShowLabel T1f08 where showLabel _ = "t1f08"

t1f08 :: T1f08
t1f08 = proxy

---------------------------------------------------------------------------
-- T1f09 Field
---------------------------------------------------------------------------

data T1f09Tag
type T1f09 = Proxy T1f09Tag
instance ShowLabel T1f09 where showLabel _ = "t1f09"

t1f09 :: T1f09
t1f09 = proxy

---------------------------------------------------------------------------
-- T1f10 Field
---------------------------------------------------------------------------

data T1f10Tag
type T1f10 = Proxy T1f10Tag
instance ShowLabel T1f10 where showLabel _ = "t1f10"

t1f10 :: T1f10
t1f10 = proxy

---------------------------------------------------------------------------
-- T1f11 Field
---------------------------------------------------------------------------

data T1f11Tag
type T1f11 = Proxy T1f11Tag
instance ShowLabel T1f11 where showLabel _ = "t1f11"

t1f11 :: T1f11
t1f11 = proxy

---------------------------------------------------------------------------
-- T1f12 Field
---------------------------------------------------------------------------

data T1f12Tag
type T1f12 = Proxy T1f12Tag
instance ShowLabel T1f12 where showLabel _ = "t1f12"

t1f12 :: T1f12
t1f12 = proxy

---------------------------------------------------------------------------
-- T1f13 Field
---------------------------------------------------------------------------

data T1f13Tag
type T1f13 = Proxy T1f13Tag
instance ShowLabel T1f13 where showLabel _ = "t1f13"

t1f13 :: T1f13
t1f13 = proxy

---------------------------------------------------------------------------
-- T1f14 Field
---------------------------------------------------------------------------

data T1f14Tag
type T1f14 = Proxy T1f14Tag
instance ShowLabel T1f14 where showLabel _ = "t1f14"

t1f14 :: T1f14
t1f14 = proxy

---------------------------------------------------------------------------
-- T1f15 Field
---------------------------------------------------------------------------

data T1f15Tag
type T1f15 = Proxy T1f15Tag
instance ShowLabel T1f15 where showLabel _ = "t1f15"

t1f15 :: T1f15
t1f15 = proxy

---------------------------------------------------------------------------
-- T1f16 Field
---------------------------------------------------------------------------

data T1f16Tag
type T1f16 = Proxy T1f16Tag
instance ShowLabel T1f16 where showLabel _ = "t1f16"

t1f16 :: T1f16
t1f16 = proxy

---------------------------------------------------------------------------
-- T1f21 Field
---------------------------------------------------------------------------

data T1f21Tag
type T1f21 = Proxy T1f21Tag
instance ShowLabel T1f21 where showLabel _ = "t1f21"

t1f21 :: T1f21
t1f21 = proxy

---------------------------------------------------------------------------
-- T1f22 Field
---------------------------------------------------------------------------

data T1f22Tag
type T1f22 = Proxy T1f22Tag
instance ShowLabel T1f22 where showLabel _ = "t1f22"

t1f22 :: T1f22
t1f22 = proxy

---------------------------------------------------------------------------
-- T1f23 Field
---------------------------------------------------------------------------

data T1f23Tag
type T1f23 = Proxy T1f23Tag
instance ShowLabel T1f23 where showLabel _ = "t1f23"

t1f23 :: T1f23
t1f23 = proxy

---------------------------------------------------------------------------
-- T1f24 Field
---------------------------------------------------------------------------

data T1f24Tag
type T1f24 = Proxy T1f24Tag
instance ShowLabel T1f24 where showLabel _ = "t1f24"

t1f24 :: T1f24
t1f24 = proxy
