#!/bin/sh

HTOOLKIT_CVS=:pserver:anonymous@cvs.sourceforge.net:/cvsroot/htoolkit

UNIXODBC_DIR=/usr
#UNIXODBC_DIR=/usr/local/dp03-7/unixODBC-2.2.6

HUGS_DIR=/usr/lib/hugs
#HUGS_DIR=/usr/local/dp03-7/hugs98-Nov2003/lib/hugs


rm -rf HSQL
cvs -d $HTOOLKIT_CVS export -D tomorrow HSQL || exit 1

cd HSQL || exit 1
patch -p0 < ../HSQL-hugs.patch || exit 1
patch -p0 < ../HSQL-desc.patch || exit 1

autoconf
./configure --enable-odbc \
CPPFLAGS=-I$UNIXODBC_DIR/include LDFLAGS=-L$UNIXODBC_DIR/lib \
--enable-hugs --with-hugs-dir=$HUGS_DIR || exit 1

make || exit 1
